import { createRouter, createWebHistory } from 'vue-router'
import Home from '@/views/Home.vue'
import Pricing from '@/views/Pricing.vue'
import Gallery from '@/views/Gallery.vue'
import FAQ from '@/views/FAQ.vue'

const routes = [
	{
		path: '/',
		name: 'home',
		component: Home,
		meta: {
			title: 'Consystnt — Your brand, everywhere. Effortlessly.',
			description: 'Stop recreating your visual identity for every platform. Consystnt learns your style once, then generates on-brand content across Instagram, TikTok, and beyond.'
		}
	},
	{
		path: '/pricing',
		name: 'pricing',
		component: Pricing,
		meta: {
			title: 'Pricing — Consystnt',
			description: 'Simple, transparent pricing for consistent brand content across all platforms. Plans start at $19/month with 37% margin baseline.'
		}
	},
	{
		path: '/gallery',
		name: 'gallery',
		component: Gallery,
		meta: {
			title: 'Gallery — Consystnt',
			description: 'See examples of consistent branding across platforms. Real content generated by our AI persona system.'
		}
	},
	{
		path: '/faq',
		name: 'faq',
		component: FAQ,
		meta: {
			title: 'FAQ — Consystnt',
			description: 'Frequently asked questions about Consystnt, AI persona training, and multi-platform content generation.'
		}
	}
]

const router = createRouter({
	history: createWebHistory(),
	routes,
	scrollBehavior(to, from, savedPosition) {
		if (savedPosition) {
			return savedPosition
		}
		return { top: 0 }
	}
})

router.beforeEach((to, from, next) => {
	if (to.meta.title) {
		document.title = to.meta.title
	}
	if (to.meta.description) {
		const metaDescription = document.querySelector('meta[name="description"]')
		if (metaDescription) {
			metaDescription.setAttribute('content', to.meta.description)
		}
	}
	next()
})

export default router
